[package]
name = "sfss"
description = "Stupid Fast Scoop Search"
version = "1.0.0"
edition = "2021"

[profile.release]
strip = true
codegen-units = 1

[dependencies]
clap = { version = "4.0.18", features = ["derive"] }
dirs = "4.0.0"
rayon = "1.5.3"
regex = "1.6.0"
rust_search = "0.1.3"
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.87"
